### ISSUE TITLE
Cannot get CryptoKey from secure storage with AWS CloudHSM

### ISSUE THREAD

**Issue by chronorus** [PeculiarVentures/xadesjs#108]
Hi, I got the follow error when using xadesjs to sign the XML file, but signing function in "node-webcrypto-p11",  works fine. Is there something working the my attached code? Thanks.

(node:23374) UnhandledPromiseRejectionWarning: Error: Cannot get CryptoKey from secure storage
    at getCryptoKey (/home/ec2-user/etax/nodejs/node_modules/@peculiar/webcrypto/build/webcrypto.js:90:15)
    at RsaSsaProvider.checkCryptoKey (/home/ec2-user/etax/nodejs/node_modules/@peculiar/webcrypto/build/webcrypto.js:1010:29)
    at RsaSsaProvider.checkSign (/home/ec2-user/etax/nodejs/node_modules/webcrypto-core/build/webcrypto-core.js:145:14)
    at RsaSsaProvider.sign (/home/ec2-user/etax/nodejs/node_modules/webcrypto-core/build/webcrypto-core.js:139:24)
    at SubtleCrypto.sign (/home/ec2-user/etax/nodejs/node_modules/webcrypto-core/build/webcrypto-core.js:778:39)
    at RsaPkcs1Sha256.Sign (/home/ec2-user/etax/nodejs/node_modules/xmldsigjs/build/index.js:65:42)
    at SignedXml.Sign (/home/ec2-user/etax/nodejs/node_modules/xmldsigjs/build/index.js:2387:37)

[samplecode.txt](https://github.com/PeculiarVentures/xadesjs/files/5321104/samplecode.txt)

**Comment by microshine** [comment]
I fixed and published `node-webcrypto-p11` module today. Please update that module and try again.

Here is my example. It works find with `SoftHSM` PKCS#11 provider 

```js
var assert = require("assert");
var fs = require("fs");
var xadesjs = require("xadesjs");
const { Crypto } = require("node-webcrypto-p11");

const config = {
  library: "/usr/local/lib/softhsm/libsofthsm2.so",
  name: "SoftHSM",
  slot: 0,
  pin: "12345"
};

const crypto = new Crypto(config)
xadesjs.Application.setEngine('pkcs11', crypto)

async function findKey(id, type) {
  const keys = await crypto.keyStorage.keys();
  const keyId = keys.find(o => {
    const [t, , i] = o.split("-");
    return t === type && i === id;
  });
  if (keyId) {
    return await crypto.keyStorage.getItem(keyId);
  }
  return null;
}

async function findCert(id) {
  const certs = await crypto.certStorage.keys();
  const certId = certs.find(o => {
    const [t, , i] = o.split("-");
    return t === "x509" && i === id;
  });
  if (certId) {
    return await crypto.certStorage.getItem(certId);
  }
  return null;
}

async function getKeyPair(id) {
  const privateKey = await findKey(id, "private");
  assert(privateKey, `Cannot find a private key by id '${id}'`);

  const publicKey = await findKey(id, "public");
  assert(publicKey, `Cannot find a public key by id '${id}'`);


  return {
    privateKey,
    publicKey,
    certificate: await findCert(id),
  }
}

async function signXml(xmlString, keys, algorithm) {
  var xmlDoc = xadesjs.Parse(xmlString);
  var signedXml = new xadesjs.SignedXml();
  var { privateKey, publicKey, certificate } = keys;
  const options = {
    // options
    keyValue: publicKey,
    // keyValue: keypairLocal.publicKey,
    references: [{ hash: "SHA-256", transforms: ["enveloped"] }],
    productionPlace: {
      country: "Thailand",
      state: "State",
      city: "City",
      code: "Code",
    },
  }
  if (certificate) {
    const raw = await crypto.certStorage.exportCert("raw", certificate);
    options.x509 = [options.signingCertificate = xadesjs.Convert.ToBase64Url(raw)];
  }
  const signature = await signedXml.Sign(
    // Signing document
    algorithm, // algorithm
    privateKey, // key
    xmlDoc, // document
    options,
  );

  return signature.toString();
}

async function main() {
  const xmlString = "<root><test/></root>"

  const keyPair = await getKeyPair("c1d9c0f309f87dae1b00665c1490dec5");

  const algorithm = { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" };
  const signature = await signXml(xmlString, keyPair, algorithm)
  console.log(signature)
}

main().catch(e => console.error(e));
```

### Out
```xml
<ds:Signature Id="id-120d47a099fc" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>xzY++9vYg1qfRKwdjD9svMpYWIIcMZgyXXVQHLFQh0o=</ds:DigestValue></ds:Reference><ds:Reference URI="#xades-id-120d47a099fc" Type="http://uri.etsi.org/01903#SignedProperties"><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>+zQmlns5cSfM+NbevFl3TM1Go9qYnhnppuJcgitwH3M=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>Db4OjqVxZbZAJas2Zo/BkQ8LZDo+mKy+g7oZPC4ulqUmA+iUHDTjLGawbEPQRL9g8y2k9qUS7oMrqcnrXS87flT/NDcFT9/EJ6ahRHmkqU0UnzhcfCCjrptxmLdsLEFHV2KKJi+IAIWUe2r5WbQFlm+0KEOGFtzIMIrvnAav9o8+gHQ3Rr3UbPo4woDJEMP8pIu30KPiEF4+rm7XOuZOzSgh+OvKUF8toWTk1eyVtmGUeHfZRRuOq/jhrkIF/cHL6B7UnLcqu9xz2tUmBUrVGvf1YtSiWG4fJ/NWAp1OH+VpjJLOojptnzGyGeTkqe8EIAlluV4TmsLeYN76zpeicw==</ds:SignatureValue><ds:KeyInfo><ds:KeyValue><ds:RSAKeyValue><ds:Modulus>w3cZ1HtoA13I/k+t+argKwmMTU6viiLCsC+APB56IP7oFF4dyp6vCzKRJcY5e2jGNzN+kfe9tmFLMNlPcEg6xce+dJudz5f6UGYhkIpqXY4IuGcSFKW5umgGBo5DtBnsK55NpJ9JZmU6kjRXWZObGtlA6iuyVvz03gCi8hQNJ225SVq9rChaOpuU9oWxYl9wdRNXuc87AEHkqBdNH8Szn4vrpHnjCzlMi6IALBVBB+ja+o7VRUT6ZoLwFvhK4nlzKx0A1mjIENLli3Bjg+rKU4ndau/jTOGg3ElLttpfhruyv2X9KouumgMpDKO3PTrWRbEPkKpDZASgiqbAF7+suw==</ds:Modulus><ds:Exponent>AQAB</ds:Exponent></ds:RSAKeyValue></ds:KeyValue><ds:X509Data><ds:X509Certificate>MIICqDCCAZCgAwIBAgIBATANBgkqhkiG9w0BAQsFADAPMQ0wCwYDVQQDEwRUZXN0MB4XDTIwMTAwNTIxMzkzMloXDTIxMTAwNTIxMzkzMlowDzENMAsGA1UEAxMEVGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMN3GdR7aANdyP5Prfmq4CsJjE1Or4oiwrAvgDweeiD+6BReHcqerwsykSXGOXtoxjczfpH3vbZhSzDZT3BIOsXHvnSbnc+X+lBmIZCKal2OCLhnEhSlubpoBgaOQ7QZ7CueTaSfSWZlOpI0V1mTmxrZQOorslb89N4AovIUDSdtuUlavawoWjqblPaFsWJfcHUTV7nPOwBB5KgXTR/Es5+L66R54ws5TIuiACwVQQfo2vqO1UVE+maC8Bb4SuJ5cysdANZoyBDS5YtwY4PqylOJ3Wrv40zhoNxJS7baX4a7sr9l/SqLrpoDKQyjtz061kWxD5CqQ2QEoIqmwBe/rLsCAwEAAaMPMA0wCwYDVR0PBAQDAgCAMA0GCSqGSIb3DQEBCwUAA4IBAQAItpvkwVHRy3DL+aRAKERYdUqrO4WjzLtpcxME0AvM2/M3BrgJ62MmZy/gLGTq8XBj99SI1YEzwGvkhEG7IEE5oEKUUIV7va/KUUM/l0mivJ8ysK0aSixpYE2X/QWjgVALf1rdKLt46P1sLYkqeQv5XAY62k5JfZt0dY6MCdO0+xsG0TLvLU6k+Jj1fv2izW4T0/CtFMxbqYrIp46NZKQv/Rt7UtjzWaBO2kVjABhXDQVUNRJWxgwmFWjSEHeaOFONpwdxuP/IRbWfzo+4kLnVGXwtRB2NGTY7TfzYgoY+6qY4Iq0huX8FcU5TtZPAiXq1XHlt1n/aQZa571IFvcCl</ds:X509Certificate></ds:X509Data></ds:KeyInfo><ds:Object><xades:QualifyingProperties Target="#id-120d47a099fc" xmlns:xades="http://uri.etsi.org/01903/v1.3.2#"><xades:SignedProperties Id="xades-id-120d47a099fc"><xades:SignedSignatureProperties><xades:SigningTime>2020-10-05T21:49:00.006Z</xades:SigningTime><xades:SigningCertificate><xades:Cert><xades:CertDigest><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>DB1qitdDd/DnJNhwLR54EfE5JvFkh8ycbIzUle/lt+w=</ds:DigestValue></xades:CertDigest><xades:IssuerSerial><ds:X509IssuerName>CN=Test</ds:X509IssuerName><ds:X509SerialNumber>1</ds:X509SerialNumber></xades:IssuerSerial></xades:Cert></xades:SigningCertificate><xades:SignatureProductionPlace><xades:City>City</xades:City><xades:StateOrProvince>State</xades:StateOrProvince><xades:PostalCode>Code</xades:PostalCode><xades:CountryName>Thailand</xades:CountryName></xades:SignatureProductionPlace></xades:SignedSignatureProperties></xades:SignedProperties></xades:QualifyingProperties></ds:Object></ds:Signature>
```

**Comment by microshine** [comment]
In your error stack it throws exception from `@peculiar/webcrypto` module. Looks like `xadesjs` uses a wrong crypto engine. Do you have  one more call of `xadesjs.Application.setEngine` for that provider?

**Comment by chronorus** [comment]
Thank you for your suggestion, I will test the code by this Friday.

**Comment by chronorus** [comment]
> In your error stack it throws exception from `@peculiar/webcrypto` module. Looks like `xadesjs` uses a wrong crypto engine. Do you have one more call of `xadesjs.Application.setEngine` for that provider?

You were right, there was `@peculiar/webcrypto` module in the previous for testing purpose. Thank you for your great advice and promt respond.
