### ISSUE TITLE
Run example https://github.com/PeculiarVentures/xadesjs/issues/84 but it produces an error message: 'XMLJS0014: WebCrypto module is not found'

### ISSUE THREAD

**Issue by Jairos2015** [PeculiarVentures/xadesjs#128]
I run example (I created an example for adding multiple signing certificates: Microshine) https://github.com/PeculiarVentures/xadesjs/issues/84 but it produces an error 

message: 'XMLJS0014: WebCrypto module is not found'

node:internal/process/esm_loader:91
    internalBinding('errors').triggerUncaughtException(
                              ^
XmlError {
  prefix: 'XMLJS',
  code: 14,
  name: 'XmlError',
  message: 'XMLJS0014: WebCrypto module is not found',     
  stack: 'Error: XMLJS0014: WebCrypto module is not found\n' +
    '    at new XmlError (D:\\nodejs\\xadescert\\node_modules\\xml-core\\dist\\index.js:217:22)\n' +
    '    at get crypto [as crypto] (D:\\nodejs\\xadescert\\node_modules\\xmldsigjs\\build\\index.js:40:19)\n' +       
    '    at SignedXml.CreateQualifyingProperties (D:\\nodejs\\xadescert\\node_modules\\xadesjs\\build\\index.js:1676:54)\n' +
    '    at new SignedXml (D:\\nodejs\\xadescert\\node_modules\\xadesjs\\build\\index.js:1634:14)\n' +
    '    at file:///D:/nodejs/xadescert/index.js:27:19'    
}

Node.js v18.4.0

Please help me.

Packages used:
import * as xmldsig from "xmldsigjs";
import { Crypto } from "@peculiar/webcrypto";
import * as x509 from "@peculiar/x509";
import * as xmldom from "xmldom";
import * as xades from "xadesjs";

const crypto = new Crypto();
x509.cryptoProvider.set(crypto);

**Comment by tjomk** [comment]
```
import { Crypto as WebCrypto } from '@peculiar/webcrypto';
import * as xadesjs from 'xadesjs';

xadesjs.Application.setEngine('NodeJS', new WebCrypto());
```
